export const icons = {
    foodpakag: require('../../assets/images/foodpakag.png'),
    fruits: require('../../assets/images/fruits.png'),
     milk: require('../../assets/images/milk.png'),
    vegetable: require('../../assets/images/vegetable.png'),
    foodLogo: require('../../assets/images/foodLogo.png'),
    foodpakag: require('../../assets/images/foodpakag.png'),
    loginfoodimages: require('../../assets/images/loginfoodimages.png'),
    siginfoodimage: require('../../assets/images/siginfoodimage.png'),
    otpfoodimg: require('../../assets/images/otpfoodimg.png'),
    down: require('../../assets/images/down.png'),
    google: require('../../assets/images/google.png'),
    facebook: require('../../assets/images/facebook.png'),
    otpfoodicon: require('../../assets/images/otpfoodicon.png'),
    hamburger: require('../../assets/images/hamburger.png'),
    trolly: require('../../assets/images/trolly.png'),
    foodprofileimg: require('../../assets/images/foodprofileimg.png'),
    user: require('../../assets/images/user.png'),
    phonecall: require('../../assets/images/phonecall.png'),
    share: require('../../assets/images/share.png'),
    logout: require('../../assets/images/logout.png'),
    search: require('../../assets/images/search.png'),
    grapes: require('../../assets/images/grapes.png'),
    papaya: require('../../assets/images/papaya.png'),
    banana: require('../../assets/images/banana.png'),
    appled: require('../../assets/images/appled.png'),
    avocado: require('../../assets/images/avocado.png'),
    orange: require('../../assets/images/orange.png'),
    tameto: require('../../assets/images/tameto.png'),
    ladyfinger: require('../../assets/images/ladyfinger.png'),
    cabegge: require('../../assets/images/cabegge.png'),
    cauliflower: require('../../assets/images/cauliflower.png'),
    suran: require('../../assets/images/suran.png'),
    redcabbge: require('../../assets/images/redcabbge.png'),
    heart: require('../../assets/images/heart.png'),
    heartline: require('../../assets/images/heartline.png'),
    plus: require('../../assets/images/plus.png'),
    nutella: require('../../assets/images/nutella.png'),
    hockory: require('../../assets/images/hockory.png'),
    watermelonseed: require('../../assets/images/watermelonseed.png'),
    nachos:require('../../assets/images/nachos.png'),
    potatochips:require('../../assets/images/potatochips.png'),
    Cookies:require('../../assets/images/Cookies.png'),
    almondmilk:require('../../assets/images/almondmilk.png'),
    Coconut:require('../../assets/images/Coconut.png'),
    oatsmil:require('../../assets/images/oatsmil.png'),
    Cowmilktwo:require('../../assets/images/Cowmilktwo.png'),
    allseedmilk:require('../../assets/images/allseedmilk.png'),
    drymilk:require('../../assets/images/drymilk.png'),
    setimg:require('../../assets/images/setimg.png'),
    grayhome:require('../../assets/images/grayhome.png'),
    likered:require('../../assets/images/likered.png'),
    view:require('../../assets/images/view.png'),
    hidden:require('../../assets/images/hidden.png'),
    forgotpasswor:require('../../assets/images/forgotpasswor.png'),
    minus:require('../../assets/images/minus.png'),
    add:require('../../assets/images/add.png'),
    check:require('../../assets/images/check.png'),
    close:require('../../assets/images/close.png'),
    email:require('../../assets/images/email.png'),
    telephonecall:require('../../assets/images/telephonecall.png'),
    foodoffercardone:require('../../assets/images/foodoffercardone.png'),
    foodoffertwo:require('../../assets/images/foodoffertwo.png'),
    offerthreee:require('../../assets/images/offerthreee.png'),
    back:require('../../assets/images/back.png'),
    star:require('../../assets/images/star.png'),
    starline:require('../../assets/images/starline.png'),
    privacypolicy:require('../../assets/images/privacypolicy.png'),
    foodcooking:require('../../assets/images/foodcooking.png'),
    fooddeliverboy:require('../../assets/images/fooddeliverboy.png'),
    buygrocery:require('../../assets/images/buygrocery.png'),
    mastercard:require('../../assets/images/mastercard.png'),
    visacard:require('../../assets/images/visacard.png'),
    bcacrad:require('../../assets/images/bcacrad.png'),
    payplecard:require('../../assets/images/payplecard.png'),
    plusone:require('../../assets/images/plusone.png'),
    mastercardimg:require('../../assets/images/mastercardimg.png'),
    visacareimag:require('../../assets/images/visacareimag.png'),
    paypleimages:require('../../assets/images/paypleimages.png'),
    bcaCardimges:require('../../assets/images/bcaCardimges.png'),
    calendar:require('../../assets/images/calendar.png'),
    question:require('../../assets/images/question.png'),
    info:require('../../assets/images/info.png'),
    backtow:require('../../assets/images/backtow.png'),
    pin:require('../../assets/images/pin.png'),
    creditcard:require('../../assets/images/creditcard.png'),
    twotrueicon:require('../../assets/images/twotrueicon.png'),
    paypal:require('../../assets/images/paypal.png'),
    applelogo:require('../../assets/images/applelogo.png'),
    saveinstagram:require('../../assets/images/saveinstagram.png'),
    
}