import InFormatiom from "../Screen/InFormatiom/InFormatiom";

export const string = {
  logout:'LogOut',
  ForgetPassword:"Forgot Password ?",
  dontworry: "Don't worry! Please enter the email\naddress linked with your account.",
  login:'Login',
  ifyouare:"If you are new user click here ",
  submit:'Submit',
  getotp:'Get OTP ',
  or:'OR',
  CVV:'CVV',
  continuewithgoogle:'Continue with Google',
  continuewithfacebook:'Continue with Facebook',
  Profiles:"Profiles",
  order:'Orders',
  contactus:'Contact us',
  shar:'Share',
  LogOut:'LogOut',
  InFormatiom:'Informatiom',
  DarkThume:'Dark Thume',
  veg:'Veg',
  fruits:'Fruits',
  packed:'Packed',
  Milk:'Milk', 
  banana:'Banana',
  ForgotPassword:"Forgot Password?",
  save:'Save',
  Address:"Address",
  Profile:"Profile",
  contactUs:'Contact Us',
  loction:'Your Location',
  chnages:"CHANGE",
  completeaddress:"Completed Address*",
  favourites:"Favourites",
  gotocart:'Go To Cart',
  subtotale:'SubTotal',
  discount:'Discount',
  total:'Total',
  Cackout:'CHECKOUT',
  mastercard:'mastercard',
  AddNewCard:'Add New Card',
  aeryousure:'Are you sure you want leave ?',
  aeryousureoder:'Are you sure add review oder ?',
  speacialoffone:'Special Offer 1',
  speacialofftwo:'Special Offer 2',
  speacialoffthree:'Special Offer 3',
  limitedtime:'Limited Time Only',
  thisweekedonly:'This weekend Olny',
  reviewoder:'Add Review ',
  add:'Add',
  home:'Home',
  ITEMS:"ITEMS",
  TOTAL:"TOTAL",
  rating:'Rating',
  PaymentMethods:"Payment Methods",
  rate:"Rate this Product",
  ORDEREDON:"ORDERED ON",
  BuyGrocery:'Buy Grocery',
  FirstDelivery:"First Delivery",
  tastyfood:"Tasty food",
  payusing:"Pay Using : ",
  chnagesplyament:'Change Payment Method',
  Savesplyament:'Save Payment Method',
  addnewpaymeny:'Add New Payment Method :',
  addPaymentMethod:'Add Payment Method',
  loremipsum:'Lorem Ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent livero.',
  fruitsdatails:'Legumes or pulses contain nutrients that are especially valuable. Legumes need to be cooked before they are eaten – this improves their nutritional quality, aids digestion and eliminates any harmful toxins. Legumes come in many forms including: red foods – like tomatoes and watermelon. These contain lycopene, which is thought to be important for fighting prostate cancer and heart disease'
  ,cardnumber:'Card Number',
  CardHolderName:'Card Holder Name',
  expirydate:'Expiry Date', 
  confrom:'CONFRIM PAYMENT',
  continueshopp:'CONTINUE SHOPPING',
  thanksyoufro:'Thanks you for purcahsing.',
  yourorderwillve:'Your order will be shipped in 2-4 internation days.',
  Thanks:'Thanks!',
  orchex:'Or Checkout With',
  Pay:'Pay',
  Checkout:"Checkout"
}
